name: zetkin
channels:
  - defaults
  - conda-forge
dependencies:
  - python[version='>=3']
  - phonenumbers
  - requests
  - yaml
  - pyyaml
  - python-dotenv
  - python-dateutil
  - pyjwt
  - selenium
